import Head from "next/head";
import { brandName } from "@/constants/common";


export default function Home() {
  return (
    <>
      <Head>
        <title>{brandName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="d-flex flex-row-reverse justify-content-center gap-5">
          <p>Home</p>
        </div>
      </div>
    </>
  );
}
