import { brandName } from "@/constants/common";
import Head from "next/head";
import { FC } from "react";

const PublicLayout: FC<any> = ({ children }) => {
  return (
    <>
      <Head>
        <title>{brandName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        background: `url(/pageBackground.png) no-repeat fixed`,
        backgroundSize: '100% 100%',
      }}>
        {children}
      </div>
    </>
  );
};

export default PublicLayout;
